<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>hydra</artifactId>
        <groupId>com.pinecone.hydra</groupId>
        <version>2.5.1</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.pinecone.hydra.sdk.grpc</groupId>
    <artifactId>hydra-lib-grpc-service-sdk</artifactId>
    <version>1.2.1</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <grpc.version>1.62.2</grpc.version>
        <protobuf.version>4.28.2</protobuf.version>
        <protoc.version>4.28.2</protoc.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.pinecone</groupId>
            <artifactId>pinecone</artifactId>
            <version>2.5.1</version>
            <scope>compile</scope>
        </dependency>


        <!-- gRPC -->
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-netty-shaded</artifactId>
            <version>${grpc.version}</version>
        </dependency>

        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-protobuf</artifactId>
            <version>${grpc.version}</version>
        </dependency>

        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-stub</artifactId>
            <version>${grpc.version}</version>
        </dependency>

        <!-- 必须：Java 9+ 需要 -->
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <version>1.3.5</version>
        </dependency>
        <dependency>
            <groupId>com.pinecone.hydra.kernel</groupId>
            <artifactId>hydra-service-control</artifactId>
            <version>2.1.0</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>
