// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service_meta.proto
// Protobuf Java Version: 4.28.2

package com.acorn.redqueen.service.registry.grpc.protocol.meta.proto;

/**
 * Protobuf type {@code CreateNewServiceRequest}
 */
public final class CreateNewServiceRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:CreateNewServiceRequest)
    CreateNewServiceRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      CreateNewServiceRequest.class.getName());
  }
  // Use CreateNewServiceRequest.newBuilder() to construct.
  private CreateNewServiceRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CreateNewServiceRequest() {
    parentAppPath_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaProto.internal_static_CreateNewServiceRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaProto.internal_static_CreateNewServiceRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest.class, com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest.Builder.class);
  }

  private int bitField0_;
  public static final int PARENTAPPPATH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object parentAppPath_ = "";
  /**
   * <code>string parentAppPath = 1;</code>
   * @return The parentAppPath.
   */
  @java.lang.Override
  public java.lang.String getParentAppPath() {
    java.lang.Object ref = parentAppPath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parentAppPath_ = s;
      return s;
    }
  }
  /**
   * <code>string parentAppPath = 1;</code>
   * @return The bytes for parentAppPath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParentAppPathBytes() {
    java.lang.Object ref = parentAppPath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parentAppPath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int META_FIELD_NUMBER = 2;
  private com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO meta_;
  /**
   * <code>.ServiceMetaDTO meta = 2;</code>
   * @return Whether the meta field is set.
   */
  @java.lang.Override
  public boolean hasMeta() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.ServiceMetaDTO meta = 2;</code>
   * @return The meta.
   */
  @java.lang.Override
  public com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO getMeta() {
    return meta_ == null ? com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO.getDefaultInstance() : meta_;
  }
  /**
   * <code>.ServiceMetaDTO meta = 2;</code>
   */
  @java.lang.Override
  public com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTOOrBuilder getMetaOrBuilder() {
    return meta_ == null ? com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO.getDefaultInstance() : meta_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(parentAppPath_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, parentAppPath_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getMeta());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(parentAppPath_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, parentAppPath_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMeta());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest)) {
      return super.equals(obj);
    }
    com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest other = (com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest) obj;

    if (!getParentAppPath()
        .equals(other.getParentAppPath())) return false;
    if (hasMeta() != other.hasMeta()) return false;
    if (hasMeta()) {
      if (!getMeta()
          .equals(other.getMeta())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PARENTAPPPATH_FIELD_NUMBER;
    hash = (53 * hash) + getParentAppPath().hashCode();
    if (hasMeta()) {
      hash = (37 * hash) + META_FIELD_NUMBER;
      hash = (53 * hash) + getMeta().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CreateNewServiceRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CreateNewServiceRequest)
      com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaProto.internal_static_CreateNewServiceRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaProto.internal_static_CreateNewServiceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest.class, com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest.Builder.class);
    }

    // Construct using com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getMetaFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      parentAppPath_ = "";
      meta_ = null;
      if (metaBuilder_ != null) {
        metaBuilder_.dispose();
        metaBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaProto.internal_static_CreateNewServiceRequest_descriptor;
    }

    @java.lang.Override
    public com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest getDefaultInstanceForType() {
      return com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest build() {
      com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest buildPartial() {
      com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest result = new com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.parentAppPath_ = parentAppPath_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.meta_ = metaBuilder_ == null
            ? meta_
            : metaBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest) {
        return mergeFrom((com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest other) {
      if (other == com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest.getDefaultInstance()) return this;
      if (!other.getParentAppPath().isEmpty()) {
        parentAppPath_ = other.parentAppPath_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasMeta()) {
        mergeMeta(other.getMeta());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              parentAppPath_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getMetaFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object parentAppPath_ = "";
    /**
     * <code>string parentAppPath = 1;</code>
     * @return The parentAppPath.
     */
    public java.lang.String getParentAppPath() {
      java.lang.Object ref = parentAppPath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parentAppPath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string parentAppPath = 1;</code>
     * @return The bytes for parentAppPath.
     */
    public com.google.protobuf.ByteString
        getParentAppPathBytes() {
      java.lang.Object ref = parentAppPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parentAppPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string parentAppPath = 1;</code>
     * @param value The parentAppPath to set.
     * @return This builder for chaining.
     */
    public Builder setParentAppPath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      parentAppPath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string parentAppPath = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearParentAppPath() {
      parentAppPath_ = getDefaultInstance().getParentAppPath();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string parentAppPath = 1;</code>
     * @param value The bytes for parentAppPath to set.
     * @return This builder for chaining.
     */
    public Builder setParentAppPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      parentAppPath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO meta_;
    private com.google.protobuf.SingleFieldBuilder<
        com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO, com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO.Builder, com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTOOrBuilder> metaBuilder_;
    /**
     * <code>.ServiceMetaDTO meta = 2;</code>
     * @return Whether the meta field is set.
     */
    public boolean hasMeta() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.ServiceMetaDTO meta = 2;</code>
     * @return The meta.
     */
    public com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO getMeta() {
      if (metaBuilder_ == null) {
        return meta_ == null ? com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO.getDefaultInstance() : meta_;
      } else {
        return metaBuilder_.getMessage();
      }
    }
    /**
     * <code>.ServiceMetaDTO meta = 2;</code>
     */
    public Builder setMeta(com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO value) {
      if (metaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        meta_ = value;
      } else {
        metaBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.ServiceMetaDTO meta = 2;</code>
     */
    public Builder setMeta(
        com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO.Builder builderForValue) {
      if (metaBuilder_ == null) {
        meta_ = builderForValue.build();
      } else {
        metaBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.ServiceMetaDTO meta = 2;</code>
     */
    public Builder mergeMeta(com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO value) {
      if (metaBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          meta_ != null &&
          meta_ != com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO.getDefaultInstance()) {
          getMetaBuilder().mergeFrom(value);
        } else {
          meta_ = value;
        }
      } else {
        metaBuilder_.mergeFrom(value);
      }
      if (meta_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.ServiceMetaDTO meta = 2;</code>
     */
    public Builder clearMeta() {
      bitField0_ = (bitField0_ & ~0x00000002);
      meta_ = null;
      if (metaBuilder_ != null) {
        metaBuilder_.dispose();
        metaBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.ServiceMetaDTO meta = 2;</code>
     */
    public com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO.Builder getMetaBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getMetaFieldBuilder().getBuilder();
    }
    /**
     * <code>.ServiceMetaDTO meta = 2;</code>
     */
    public com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTOOrBuilder getMetaOrBuilder() {
      if (metaBuilder_ != null) {
        return metaBuilder_.getMessageOrBuilder();
      } else {
        return meta_ == null ?
            com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO.getDefaultInstance() : meta_;
      }
    }
    /**
     * <code>.ServiceMetaDTO meta = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO, com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO.Builder, com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTOOrBuilder> 
        getMetaFieldBuilder() {
      if (metaBuilder_ == null) {
        metaBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO, com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO.Builder, com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTOOrBuilder>(
                getMeta(),
                getParentForChildren(),
                isClean());
        meta_ = null;
      }
      return metaBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:CreateNewServiceRequest)
  }

  // @@protoc_insertion_point(class_scope:CreateNewServiceRequest)
  private static final com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest();
  }

  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateNewServiceRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateNewServiceRequest>() {
    @java.lang.Override
    public CreateNewServiceRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateNewServiceRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateNewServiceRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.CreateNewServiceRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

