// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service_meta.proto
// Protobuf Java Version: 4.28.2

package com.acorn.redqueen.service.registry.grpc.protocol.meta.proto;

/**
 * Protobuf type {@code EvalCreationStatementRequest}
 */
public final class EvalCreationStatementRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:EvalCreationStatementRequest)
    EvalCreationStatementRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      EvalCreationStatementRequest.class.getName());
  }
  // Use EvalCreationStatementRequest.newBuilder() to construct.
  private EvalCreationStatementRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private EvalCreationStatementRequest() {
    jonsStatement_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaProto.internal_static_EvalCreationStatementRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaProto.internal_static_EvalCreationStatementRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest.class, com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest.Builder.class);
  }

  public static final int JONSSTATEMENT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object jonsStatement_ = "";
  /**
   * <code>string jonsStatement = 1;</code>
   * @return The jonsStatement.
   */
  @java.lang.Override
  public java.lang.String getJonsStatement() {
    java.lang.Object ref = jonsStatement_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jonsStatement_ = s;
      return s;
    }
  }
  /**
   * <code>string jonsStatement = 1;</code>
   * @return The bytes for jonsStatement.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJonsStatementBytes() {
    java.lang.Object ref = jonsStatement_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jonsStatement_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(jonsStatement_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, jonsStatement_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(jonsStatement_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, jonsStatement_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest)) {
      return super.equals(obj);
    }
    com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest other = (com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest) obj;

    if (!getJonsStatement()
        .equals(other.getJonsStatement())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + JONSSTATEMENT_FIELD_NUMBER;
    hash = (53 * hash) + getJonsStatement().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code EvalCreationStatementRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EvalCreationStatementRequest)
      com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaProto.internal_static_EvalCreationStatementRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaProto.internal_static_EvalCreationStatementRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest.class, com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest.Builder.class);
    }

    // Construct using com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      jonsStatement_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaProto.internal_static_EvalCreationStatementRequest_descriptor;
    }

    @java.lang.Override
    public com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest getDefaultInstanceForType() {
      return com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest build() {
      com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest buildPartial() {
      com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest result = new com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.jonsStatement_ = jonsStatement_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest) {
        return mergeFrom((com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest other) {
      if (other == com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest.getDefaultInstance()) return this;
      if (!other.getJonsStatement().isEmpty()) {
        jonsStatement_ = other.jonsStatement_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              jonsStatement_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object jonsStatement_ = "";
    /**
     * <code>string jonsStatement = 1;</code>
     * @return The jonsStatement.
     */
    public java.lang.String getJonsStatement() {
      java.lang.Object ref = jonsStatement_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jonsStatement_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string jonsStatement = 1;</code>
     * @return The bytes for jonsStatement.
     */
    public com.google.protobuf.ByteString
        getJonsStatementBytes() {
      java.lang.Object ref = jonsStatement_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jonsStatement_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string jonsStatement = 1;</code>
     * @param value The jonsStatement to set.
     * @return This builder for chaining.
     */
    public Builder setJonsStatement(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      jonsStatement_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string jonsStatement = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearJonsStatement() {
      jonsStatement_ = getDefaultInstance().getJonsStatement();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string jonsStatement = 1;</code>
     * @param value The bytes for jonsStatement to set.
     * @return This builder for chaining.
     */
    public Builder setJonsStatementBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      jonsStatement_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:EvalCreationStatementRequest)
  }

  // @@protoc_insertion_point(class_scope:EvalCreationStatementRequest)
  private static final com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest();
  }

  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EvalCreationStatementRequest>
      PARSER = new com.google.protobuf.AbstractParser<EvalCreationStatementRequest>() {
    @java.lang.Override
    public EvalCreationStatementRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EvalCreationStatementRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EvalCreationStatementRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.EvalCreationStatementRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

