// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service_meta.proto
// Protobuf Java Version: 4.28.2

package com.acorn.redqueen.service.registry.grpc.protocol.meta.proto;

public interface EvalCreationStatementRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EvalCreationStatementRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string jonsStatement = 1;</code>
   * @return The jonsStatement.
   */
  java.lang.String getJonsStatement();
  /**
   * <code>string jonsStatement = 1;</code>
   * @return The bytes for jonsStatement.
   */
  com.google.protobuf.ByteString
      getJonsStatementBytes();
}
