// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service_meta.proto
// Protobuf Java Version: 4.28.2

package com.acorn.redqueen.service.registry.grpc.protocol.meta.proto;

/**
 * Protobuf type {@code ServiceMetaDTO}
 */
public final class ServiceMetaDTO extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ServiceMetaDTO)
    ServiceMetaDTOOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      ServiceMetaDTO.class.getName());
  }
  // Use ServiceMetaDTO.newBuilder() to construct.
  private ServiceMetaDTO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ServiceMetaDTO() {
    guid_ = "";
    name_ = "";
    type_ = "";
    alias_ = "";
    resourceType_ = "";
    serviceType_ = "";
    displayName_ = "";
    description_ = "";
    fullName_ = "";
    groupNamespace_ = "";
    groupName_ = "";
    scenario_ = "";
    primaryImplLang_ = "";
    extraInformation_ = "";
    level_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaProto.internal_static_ServiceMetaDTO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaProto.internal_static_ServiceMetaDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO.class, com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO.Builder.class);
  }

  public static final int GUID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object guid_ = "";
  /**
   * <code>string guid = 1;</code>
   * @return The guid.
   */
  @java.lang.Override
  public java.lang.String getGuid() {
    java.lang.Object ref = guid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      guid_ = s;
      return s;
    }
  }
  /**
   * <code>string guid = 1;</code>
   * @return The bytes for guid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGuidBytes() {
    java.lang.Object ref = guid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      guid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object type_ = "";
  /**
   * <code>string type = 3;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALIAS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object alias_ = "";
  /**
   * <code>string alias = 4;</code>
   * @return The alias.
   */
  @java.lang.Override
  public java.lang.String getAlias() {
    java.lang.Object ref = alias_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      alias_ = s;
      return s;
    }
  }
  /**
   * <code>string alias = 4;</code>
   * @return The bytes for alias.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAliasBytes() {
    java.lang.Object ref = alias_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      alias_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESOURCETYPE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object resourceType_ = "";
  /**
   * <code>string resourceType = 5;</code>
   * @return The resourceType.
   */
  @java.lang.Override
  public java.lang.String getResourceType() {
    java.lang.Object ref = resourceType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resourceType_ = s;
      return s;
    }
  }
  /**
   * <code>string resourceType = 5;</code>
   * @return The bytes for resourceType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResourceTypeBytes() {
    java.lang.Object ref = resourceType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resourceType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVICETYPE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object serviceType_ = "";
  /**
   * <code>string serviceType = 6;</code>
   * @return The serviceType.
   */
  @java.lang.Override
  public java.lang.String getServiceType() {
    java.lang.Object ref = serviceType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serviceType_ = s;
      return s;
    }
  }
  /**
   * <code>string serviceType = 6;</code>
   * @return The bytes for serviceType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServiceTypeBytes() {
    java.lang.Object ref = serviceType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serviceType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAYNAME_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object displayName_ = "";
  /**
   * <code>string displayName = 7;</code>
   * @return The displayName.
   */
  @java.lang.Override
  public java.lang.String getDisplayName() {
    java.lang.Object ref = displayName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displayName_ = s;
      return s;
    }
  }
  /**
   * <code>string displayName = 7;</code>
   * @return The bytes for displayName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDisplayNameBytes() {
    java.lang.Object ref = displayName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displayName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <code>string description = 8;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 8;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FULLNAME_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fullName_ = "";
  /**
   * <code>string fullName = 9;</code>
   * @return The fullName.
   */
  @java.lang.Override
  public java.lang.String getFullName() {
    java.lang.Object ref = fullName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fullName_ = s;
      return s;
    }
  }
  /**
   * <code>string fullName = 9;</code>
   * @return The bytes for fullName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFullNameBytes() {
    java.lang.Object ref = fullName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fullName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GROUPNAMESPACE_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object groupNamespace_ = "";
  /**
   * <code>string groupNamespace = 10;</code>
   * @return The groupNamespace.
   */
  @java.lang.Override
  public java.lang.String getGroupNamespace() {
    java.lang.Object ref = groupNamespace_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      groupNamespace_ = s;
      return s;
    }
  }
  /**
   * <code>string groupNamespace = 10;</code>
   * @return The bytes for groupNamespace.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGroupNamespaceBytes() {
    java.lang.Object ref = groupNamespace_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      groupNamespace_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GROUPNAME_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object groupName_ = "";
  /**
   * <code>string groupName = 11;</code>
   * @return The groupName.
   */
  @java.lang.Override
  public java.lang.String getGroupName() {
    java.lang.Object ref = groupName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      groupName_ = s;
      return s;
    }
  }
  /**
   * <code>string groupName = 11;</code>
   * @return The bytes for groupName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGroupNameBytes() {
    java.lang.Object ref = groupName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      groupName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCENARIO_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile java.lang.Object scenario_ = "";
  /**
   * <code>string scenario = 12;</code>
   * @return The scenario.
   */
  @java.lang.Override
  public java.lang.String getScenario() {
    java.lang.Object ref = scenario_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      scenario_ = s;
      return s;
    }
  }
  /**
   * <code>string scenario = 12;</code>
   * @return The bytes for scenario.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getScenarioBytes() {
    java.lang.Object ref = scenario_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      scenario_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRIMARYIMPLLANG_FIELD_NUMBER = 13;
  @SuppressWarnings("serial")
  private volatile java.lang.Object primaryImplLang_ = "";
  /**
   * <code>string primaryImplLang = 13;</code>
   * @return The primaryImplLang.
   */
  @java.lang.Override
  public java.lang.String getPrimaryImplLang() {
    java.lang.Object ref = primaryImplLang_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      primaryImplLang_ = s;
      return s;
    }
  }
  /**
   * <code>string primaryImplLang = 13;</code>
   * @return The bytes for primaryImplLang.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPrimaryImplLangBytes() {
    java.lang.Object ref = primaryImplLang_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      primaryImplLang_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXTRAINFORMATION_FIELD_NUMBER = 14;
  @SuppressWarnings("serial")
  private volatile java.lang.Object extraInformation_ = "";
  /**
   * <code>string extraInformation = 14;</code>
   * @return The extraInformation.
   */
  @java.lang.Override
  public java.lang.String getExtraInformation() {
    java.lang.Object ref = extraInformation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      extraInformation_ = s;
      return s;
    }
  }
  /**
   * <code>string extraInformation = 14;</code>
   * @return The bytes for extraInformation.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExtraInformationBytes() {
    java.lang.Object ref = extraInformation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      extraInformation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LEVEL_FIELD_NUMBER = 15;
  @SuppressWarnings("serial")
  private volatile java.lang.Object level_ = "";
  /**
   * <code>string level = 15;</code>
   * @return The level.
   */
  @java.lang.Override
  public java.lang.String getLevel() {
    java.lang.Object ref = level_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      level_ = s;
      return s;
    }
  }
  /**
   * <code>string level = 15;</code>
   * @return The bytes for level.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLevelBytes() {
    java.lang.Object ref = level_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      level_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(guid_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, guid_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, type_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(alias_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, alias_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resourceType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, resourceType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serviceType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, serviceType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(displayName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, displayName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(fullName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, fullName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(groupNamespace_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, groupNamespace_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(groupName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 11, groupName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(scenario_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 12, scenario_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(primaryImplLang_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 13, primaryImplLang_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(extraInformation_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 14, extraInformation_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(level_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 15, level_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(guid_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, guid_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, type_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(alias_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, alias_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resourceType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, resourceType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serviceType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, serviceType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(displayName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, displayName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(fullName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, fullName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(groupNamespace_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, groupNamespace_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(groupName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(11, groupName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(scenario_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(12, scenario_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(primaryImplLang_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(13, primaryImplLang_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(extraInformation_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(14, extraInformation_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(level_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(15, level_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO)) {
      return super.equals(obj);
    }
    com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO other = (com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO) obj;

    if (!getGuid()
        .equals(other.getGuid())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getType()
        .equals(other.getType())) return false;
    if (!getAlias()
        .equals(other.getAlias())) return false;
    if (!getResourceType()
        .equals(other.getResourceType())) return false;
    if (!getServiceType()
        .equals(other.getServiceType())) return false;
    if (!getDisplayName()
        .equals(other.getDisplayName())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getFullName()
        .equals(other.getFullName())) return false;
    if (!getGroupNamespace()
        .equals(other.getGroupNamespace())) return false;
    if (!getGroupName()
        .equals(other.getGroupName())) return false;
    if (!getScenario()
        .equals(other.getScenario())) return false;
    if (!getPrimaryImplLang()
        .equals(other.getPrimaryImplLang())) return false;
    if (!getExtraInformation()
        .equals(other.getExtraInformation())) return false;
    if (!getLevel()
        .equals(other.getLevel())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + GUID_FIELD_NUMBER;
    hash = (53 * hash) + getGuid().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + ALIAS_FIELD_NUMBER;
    hash = (53 * hash) + getAlias().hashCode();
    hash = (37 * hash) + RESOURCETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getResourceType().hashCode();
    hash = (37 * hash) + SERVICETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getServiceType().hashCode();
    hash = (37 * hash) + DISPLAYNAME_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayName().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + FULLNAME_FIELD_NUMBER;
    hash = (53 * hash) + getFullName().hashCode();
    hash = (37 * hash) + GROUPNAMESPACE_FIELD_NUMBER;
    hash = (53 * hash) + getGroupNamespace().hashCode();
    hash = (37 * hash) + GROUPNAME_FIELD_NUMBER;
    hash = (53 * hash) + getGroupName().hashCode();
    hash = (37 * hash) + SCENARIO_FIELD_NUMBER;
    hash = (53 * hash) + getScenario().hashCode();
    hash = (37 * hash) + PRIMARYIMPLLANG_FIELD_NUMBER;
    hash = (53 * hash) + getPrimaryImplLang().hashCode();
    hash = (37 * hash) + EXTRAINFORMATION_FIELD_NUMBER;
    hash = (53 * hash) + getExtraInformation().hashCode();
    hash = (37 * hash) + LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getLevel().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ServiceMetaDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ServiceMetaDTO)
      com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaProto.internal_static_ServiceMetaDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaProto.internal_static_ServiceMetaDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO.class, com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO.Builder.class);
    }

    // Construct using com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      guid_ = "";
      name_ = "";
      type_ = "";
      alias_ = "";
      resourceType_ = "";
      serviceType_ = "";
      displayName_ = "";
      description_ = "";
      fullName_ = "";
      groupNamespace_ = "";
      groupName_ = "";
      scenario_ = "";
      primaryImplLang_ = "";
      extraInformation_ = "";
      level_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaProto.internal_static_ServiceMetaDTO_descriptor;
    }

    @java.lang.Override
    public com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO getDefaultInstanceForType() {
      return com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO.getDefaultInstance();
    }

    @java.lang.Override
    public com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO build() {
      com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO buildPartial() {
      com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO result = new com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.guid_ = guid_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.alias_ = alias_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.resourceType_ = resourceType_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.serviceType_ = serviceType_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.displayName_ = displayName_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.fullName_ = fullName_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.groupNamespace_ = groupNamespace_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.groupName_ = groupName_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.scenario_ = scenario_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.primaryImplLang_ = primaryImplLang_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.extraInformation_ = extraInformation_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.level_ = level_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO) {
        return mergeFrom((com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO other) {
      if (other == com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO.getDefaultInstance()) return this;
      if (!other.getGuid().isEmpty()) {
        guid_ = other.guid_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getAlias().isEmpty()) {
        alias_ = other.alias_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getResourceType().isEmpty()) {
        resourceType_ = other.resourceType_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getServiceType().isEmpty()) {
        serviceType_ = other.serviceType_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getDisplayName().isEmpty()) {
        displayName_ = other.displayName_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getFullName().isEmpty()) {
        fullName_ = other.fullName_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getGroupNamespace().isEmpty()) {
        groupNamespace_ = other.groupNamespace_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (!other.getGroupName().isEmpty()) {
        groupName_ = other.groupName_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (!other.getScenario().isEmpty()) {
        scenario_ = other.scenario_;
        bitField0_ |= 0x00000800;
        onChanged();
      }
      if (!other.getPrimaryImplLang().isEmpty()) {
        primaryImplLang_ = other.primaryImplLang_;
        bitField0_ |= 0x00001000;
        onChanged();
      }
      if (!other.getExtraInformation().isEmpty()) {
        extraInformation_ = other.extraInformation_;
        bitField0_ |= 0x00002000;
        onChanged();
      }
      if (!other.getLevel().isEmpty()) {
        level_ = other.level_;
        bitField0_ |= 0x00004000;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              guid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              type_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              alias_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              resourceType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              serviceType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              displayName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              fullName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              groupNamespace_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              groupName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 98: {
              scenario_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 106: {
              primaryImplLang_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            case 114: {
              extraInformation_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00002000;
              break;
            } // case 114
            case 122: {
              level_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00004000;
              break;
            } // case 122
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object guid_ = "";
    /**
     * <code>string guid = 1;</code>
     * @return The guid.
     */
    public java.lang.String getGuid() {
      java.lang.Object ref = guid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        guid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string guid = 1;</code>
     * @return The bytes for guid.
     */
    public com.google.protobuf.ByteString
        getGuidBytes() {
      java.lang.Object ref = guid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        guid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string guid = 1;</code>
     * @param value The guid to set.
     * @return This builder for chaining.
     */
    public Builder setGuid(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      guid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string guid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearGuid() {
      guid_ = getDefaultInstance().getGuid();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string guid = 1;</code>
     * @param value The bytes for guid to set.
     * @return This builder for chaining.
     */
    public Builder setGuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      guid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 3;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 3;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 3;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      type_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      type_ = getDefaultInstance().getType();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string type = 3;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      type_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object alias_ = "";
    /**
     * <code>string alias = 4;</code>
     * @return The alias.
     */
    public java.lang.String getAlias() {
      java.lang.Object ref = alias_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alias_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string alias = 4;</code>
     * @return The bytes for alias.
     */
    public com.google.protobuf.ByteString
        getAliasBytes() {
      java.lang.Object ref = alias_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alias_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string alias = 4;</code>
     * @param value The alias to set.
     * @return This builder for chaining.
     */
    public Builder setAlias(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      alias_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string alias = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlias() {
      alias_ = getDefaultInstance().getAlias();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string alias = 4;</code>
     * @param value The bytes for alias to set.
     * @return This builder for chaining.
     */
    public Builder setAliasBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      alias_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object resourceType_ = "";
    /**
     * <code>string resourceType = 5;</code>
     * @return The resourceType.
     */
    public java.lang.String getResourceType() {
      java.lang.Object ref = resourceType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resourceType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string resourceType = 5;</code>
     * @return The bytes for resourceType.
     */
    public com.google.protobuf.ByteString
        getResourceTypeBytes() {
      java.lang.Object ref = resourceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resourceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string resourceType = 5;</code>
     * @param value The resourceType to set.
     * @return This builder for chaining.
     */
    public Builder setResourceType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      resourceType_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string resourceType = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearResourceType() {
      resourceType_ = getDefaultInstance().getResourceType();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string resourceType = 5;</code>
     * @param value The bytes for resourceType to set.
     * @return This builder for chaining.
     */
    public Builder setResourceTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      resourceType_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object serviceType_ = "";
    /**
     * <code>string serviceType = 6;</code>
     * @return The serviceType.
     */
    public java.lang.String getServiceType() {
      java.lang.Object ref = serviceType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string serviceType = 6;</code>
     * @return The bytes for serviceType.
     */
    public com.google.protobuf.ByteString
        getServiceTypeBytes() {
      java.lang.Object ref = serviceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string serviceType = 6;</code>
     * @param value The serviceType to set.
     * @return This builder for chaining.
     */
    public Builder setServiceType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      serviceType_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string serviceType = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearServiceType() {
      serviceType_ = getDefaultInstance().getServiceType();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string serviceType = 6;</code>
     * @param value The bytes for serviceType to set.
     * @return This builder for chaining.
     */
    public Builder setServiceTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      serviceType_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object displayName_ = "";
    /**
     * <code>string displayName = 7;</code>
     * @return The displayName.
     */
    public java.lang.String getDisplayName() {
      java.lang.Object ref = displayName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string displayName = 7;</code>
     * @return The bytes for displayName.
     */
    public com.google.protobuf.ByteString
        getDisplayNameBytes() {
      java.lang.Object ref = displayName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string displayName = 7;</code>
     * @param value The displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      displayName_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string displayName = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplayName() {
      displayName_ = getDefaultInstance().getDisplayName();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string displayName = 7;</code>
     * @param value The bytes for displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      displayName_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 8;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 8;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 8;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string description = 8;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object fullName_ = "";
    /**
     * <code>string fullName = 9;</code>
     * @return The fullName.
     */
    public java.lang.String getFullName() {
      java.lang.Object ref = fullName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fullName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fullName = 9;</code>
     * @return The bytes for fullName.
     */
    public com.google.protobuf.ByteString
        getFullNameBytes() {
      java.lang.Object ref = fullName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fullName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fullName = 9;</code>
     * @param value The fullName to set.
     * @return This builder for chaining.
     */
    public Builder setFullName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fullName_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string fullName = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearFullName() {
      fullName_ = getDefaultInstance().getFullName();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string fullName = 9;</code>
     * @param value The bytes for fullName to set.
     * @return This builder for chaining.
     */
    public Builder setFullNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fullName_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object groupNamespace_ = "";
    /**
     * <code>string groupNamespace = 10;</code>
     * @return The groupNamespace.
     */
    public java.lang.String getGroupNamespace() {
      java.lang.Object ref = groupNamespace_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupNamespace_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string groupNamespace = 10;</code>
     * @return The bytes for groupNamespace.
     */
    public com.google.protobuf.ByteString
        getGroupNamespaceBytes() {
      java.lang.Object ref = groupNamespace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupNamespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string groupNamespace = 10;</code>
     * @param value The groupNamespace to set.
     * @return This builder for chaining.
     */
    public Builder setGroupNamespace(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      groupNamespace_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string groupNamespace = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupNamespace() {
      groupNamespace_ = getDefaultInstance().getGroupNamespace();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string groupNamespace = 10;</code>
     * @param value The bytes for groupNamespace to set.
     * @return This builder for chaining.
     */
    public Builder setGroupNamespaceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      groupNamespace_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private java.lang.Object groupName_ = "";
    /**
     * <code>string groupName = 11;</code>
     * @return The groupName.
     */
    public java.lang.String getGroupName() {
      java.lang.Object ref = groupName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string groupName = 11;</code>
     * @return The bytes for groupName.
     */
    public com.google.protobuf.ByteString
        getGroupNameBytes() {
      java.lang.Object ref = groupName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string groupName = 11;</code>
     * @param value The groupName to set.
     * @return This builder for chaining.
     */
    public Builder setGroupName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      groupName_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>string groupName = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupName() {
      groupName_ = getDefaultInstance().getGroupName();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>string groupName = 11;</code>
     * @param value The bytes for groupName to set.
     * @return This builder for chaining.
     */
    public Builder setGroupNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      groupName_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private java.lang.Object scenario_ = "";
    /**
     * <code>string scenario = 12;</code>
     * @return The scenario.
     */
    public java.lang.String getScenario() {
      java.lang.Object ref = scenario_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scenario_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string scenario = 12;</code>
     * @return The bytes for scenario.
     */
    public com.google.protobuf.ByteString
        getScenarioBytes() {
      java.lang.Object ref = scenario_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scenario_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string scenario = 12;</code>
     * @param value The scenario to set.
     * @return This builder for chaining.
     */
    public Builder setScenario(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      scenario_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>string scenario = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearScenario() {
      scenario_ = getDefaultInstance().getScenario();
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    /**
     * <code>string scenario = 12;</code>
     * @param value The bytes for scenario to set.
     * @return This builder for chaining.
     */
    public Builder setScenarioBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      scenario_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }

    private java.lang.Object primaryImplLang_ = "";
    /**
     * <code>string primaryImplLang = 13;</code>
     * @return The primaryImplLang.
     */
    public java.lang.String getPrimaryImplLang() {
      java.lang.Object ref = primaryImplLang_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        primaryImplLang_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string primaryImplLang = 13;</code>
     * @return The bytes for primaryImplLang.
     */
    public com.google.protobuf.ByteString
        getPrimaryImplLangBytes() {
      java.lang.Object ref = primaryImplLang_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        primaryImplLang_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string primaryImplLang = 13;</code>
     * @param value The primaryImplLang to set.
     * @return This builder for chaining.
     */
    public Builder setPrimaryImplLang(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      primaryImplLang_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>string primaryImplLang = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrimaryImplLang() {
      primaryImplLang_ = getDefaultInstance().getPrimaryImplLang();
      bitField0_ = (bitField0_ & ~0x00001000);
      onChanged();
      return this;
    }
    /**
     * <code>string primaryImplLang = 13;</code>
     * @param value The bytes for primaryImplLang to set.
     * @return This builder for chaining.
     */
    public Builder setPrimaryImplLangBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      primaryImplLang_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }

    private java.lang.Object extraInformation_ = "";
    /**
     * <code>string extraInformation = 14;</code>
     * @return The extraInformation.
     */
    public java.lang.String getExtraInformation() {
      java.lang.Object ref = extraInformation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extraInformation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string extraInformation = 14;</code>
     * @return The bytes for extraInformation.
     */
    public com.google.protobuf.ByteString
        getExtraInformationBytes() {
      java.lang.Object ref = extraInformation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extraInformation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string extraInformation = 14;</code>
     * @param value The extraInformation to set.
     * @return This builder for chaining.
     */
    public Builder setExtraInformation(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      extraInformation_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>string extraInformation = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearExtraInformation() {
      extraInformation_ = getDefaultInstance().getExtraInformation();
      bitField0_ = (bitField0_ & ~0x00002000);
      onChanged();
      return this;
    }
    /**
     * <code>string extraInformation = 14;</code>
     * @param value The bytes for extraInformation to set.
     * @return This builder for chaining.
     */
    public Builder setExtraInformationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      extraInformation_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }

    private java.lang.Object level_ = "";
    /**
     * <code>string level = 15;</code>
     * @return The level.
     */
    public java.lang.String getLevel() {
      java.lang.Object ref = level_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        level_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string level = 15;</code>
     * @return The bytes for level.
     */
    public com.google.protobuf.ByteString
        getLevelBytes() {
      java.lang.Object ref = level_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        level_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string level = 15;</code>
     * @param value The level to set.
     * @return This builder for chaining.
     */
    public Builder setLevel(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      level_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <code>string level = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearLevel() {
      level_ = getDefaultInstance().getLevel();
      bitField0_ = (bitField0_ & ~0x00004000);
      onChanged();
      return this;
    }
    /**
     * <code>string level = 15;</code>
     * @param value The bytes for level to set.
     * @return This builder for chaining.
     */
    public Builder setLevelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      level_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ServiceMetaDTO)
  }

  // @@protoc_insertion_point(class_scope:ServiceMetaDTO)
  private static final com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO();
  }

  public static com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServiceMetaDTO>
      PARSER = new com.google.protobuf.AbstractParser<ServiceMetaDTO>() {
    @java.lang.Override
    public ServiceMetaDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ServiceMetaDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServiceMetaDTO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.acorn.redqueen.service.registry.grpc.protocol.meta.proto.ServiceMetaDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

