// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service_query.proto
// Protobuf Java Version: 4.28.2

package com.acorn.redqueen.service.registry.grpc.protocol.meta.proto;

public final class ServiceQueryProto {
  private ServiceQueryProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      ServiceQueryProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FetchServicePageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FetchServicePageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FetchServiceInstancePageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FetchServiceInstancePageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_QueryServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryServiceInstanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_QueryServiceInstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FetchNamespaceChildrenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FetchNamespaceChildrenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ServiceDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceInstanceDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ServiceInstanceDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NamespaceNodeDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NamespaceNodeDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServicePageReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ServicePageReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceInstancePageReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ServiceInstancePageReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ServiceReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceInstanceReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ServiceInstanceReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NamespaceChildrenReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NamespaceChildrenReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023service_query.proto\"y\n\027FetchServicePag" +
      "eRequest\022\017\n\007keyword\030\001 \001(\t\022\025\n\rnamespaceGu" +
      "id\030\002 \001(\t\022\027\n\017applicationGuid\030\003 \001(\t\022\016\n\006off" +
      "set\030\004 \001(\005\022\r\n\005limit\030\005 \001(\005\"w\n\037FetchService" +
      "InstancePageRequest\022\023\n\013serviceGuid\030\001 \001(\t" +
      "\022\016\n\006status\030\002 \001(\t\022\020\n\010clientId\030\003 \001(\t\022\016\n\006of" +
      "fset\030\004 \001(\005\022\r\n\005limit\030\005 \001(\005\"8\n\023QueryServic" +
      "eRequest\022\023\n\013serviceGuid\030\001 \001(\t\022\014\n\004path\030\002 " +
      "\001(\t\"E\n\033QueryServiceInstanceRequest\022\024\n\014in" +
      "stanceGuid\030\001 \001(\t\022\020\n\010clientId\030\002 \001(\t\"A\n\035Fe" +
      "tchNamespaceChildrenRequest\022\022\n\nparentGui" +
      "d\030\001 \001(\t\022\014\n\004path\030\002 \001(\t\"\361\001\n\nServiceDTO\022\014\n\004" +
      "guid\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\023\n\013displayName\030" +
      "\003 \001(\t\022\023\n\013description\030\004 \001(\t\022\014\n\004type\030\005 \001(\t" +
      "\022\020\n\010fullName\030\006 \001(\t\022\026\n\016groupNamespace\030\007 \001" +
      "(\t\022\021\n\tgroupName\030\010 \001(\t\022\020\n\010scenario\030\t \001(\t\022" +
      "\027\n\017primaryImplLang\030\n \001(\t\022\030\n\020extraInforma" +
      "tion\030\013 \001(\t\022\r\n\005level\030\014 \001(\t\"\201\003\n\022ServiceIns" +
      "tanceDTO\022\014\n\004guid\030\001 \001(\t\022\023\n\013serviceGuid\030\002 " +
      "\001(\t\022\022\n\ndeployGuid\030\003 \001(\t\022\024\n\014connectionId\030" +
      "\004 \001(\t\022\020\n\010clientId\030\005 \001(\t\022\025\n\rtransportType" +
      "\030\006 \001(\t\022\025\n\rremoteAddress\030\007 \001(\t\022\030\n\020endpoin" +
      "tProtocol\030\010 \001(\t\022\024\n\014endpointHost\030\t \001(\t\022\024\n" +
      "\014endpointPort\030\n \001(\005\022\024\n\014endpointPath\030\013 \001(" +
      "\t\022\027\n\017endpointAddress\030\014 \001(\t\022\016\n\006status\030\r \001" +
      "(\t\022\024\n\014statusReason\030\016 \001(\t\022\017\n\007version\030\017 \001(" +
      "\t\022\014\n\004zone\030\020 \001(\t\022\016\n\006weight\030\021 \001(\005\022\024\n\014metad" +
      "ataJson\030\022 \001(\t\"_\n\020NamespaceNodeDTO\022\014\n\004gui" +
      "d\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\014\n\004type\030\003 \001(\t\022\023\n\013d" +
      "escription\030\004 \001(\t\022\014\n\004leaf\030\005 \001(\010\"\\\n\020Servic" +
      "ePageReply\022\032\n\005items\030\001 \003(\0132\013.ServiceDTO\022\r" +
      "\n\005total\030\002 \001(\003\022\016\n\006offset\030\003 \001(\005\022\r\n\005limit\030\004" +
      " \001(\005\"l\n\030ServiceInstancePageReply\022\"\n\005item" +
      "s\030\001 \003(\0132\023.ServiceInstanceDTO\022\r\n\005total\030\002 " +
      "\001(\003\022\016\n\006offset\030\003 \001(\005\022\r\n\005limit\030\004 \001(\005\",\n\014Se" +
      "rviceReply\022\034\n\007service\030\001 \001(\0132\013.ServiceDTO" +
      "\"=\n\024ServiceInstanceReply\022%\n\010instance\030\001 \001" +
      "(\0132\023.ServiceInstanceDTO\":\n\026NamespaceChil" +
      "drenReply\022 \n\005items\030\001 \003(\0132\021.NamespaceNode" +
      "DTO2\375\002\n\014ServiceQuery\022?\n\020FetchServicePage" +
      "\022\030.FetchServicePageRequest\032\021.ServicePage" +
      "Reply\022W\n\030FetchServiceInstancePage\022 .Fetc" +
      "hServiceInstancePageRequest\032\031.ServiceIns" +
      "tancePageReply\0223\n\014QueryService\022\024.QuerySe" +
      "rviceRequest\032\r.ServiceReply\022K\n\024QueryServ" +
      "iceInstance\022\034.QueryServiceInstanceReques" +
      "t\032\025.ServiceInstanceReply\022Q\n\026FetchNamespa" +
      "ceChildren\022\036.FetchNamespaceChildrenReque" +
      "st\032\027.NamespaceChildrenReplyB\\\nEcom.pinec" +
      "one.hydra.service.registry.server.transp" +
      "ort.grpc.query.protoB\021ServiceQueryProtoP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FetchServicePageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FetchServicePageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FetchServicePageRequest_descriptor,
        new java.lang.String[] { "Keyword", "NamespaceGuid", "ApplicationGuid", "Offset", "Limit", });
    internal_static_FetchServiceInstancePageRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FetchServiceInstancePageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FetchServiceInstancePageRequest_descriptor,
        new java.lang.String[] { "ServiceGuid", "Status", "ClientId", "Offset", "Limit", });
    internal_static_QueryServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_QueryServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_QueryServiceRequest_descriptor,
        new java.lang.String[] { "ServiceGuid", "Path", });
    internal_static_QueryServiceInstanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_QueryServiceInstanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_QueryServiceInstanceRequest_descriptor,
        new java.lang.String[] { "InstanceGuid", "ClientId", });
    internal_static_FetchNamespaceChildrenRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_FetchNamespaceChildrenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FetchNamespaceChildrenRequest_descriptor,
        new java.lang.String[] { "ParentGuid", "Path", });
    internal_static_ServiceDTO_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ServiceDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ServiceDTO_descriptor,
        new java.lang.String[] { "Guid", "Name", "DisplayName", "Description", "Type", "FullName", "GroupNamespace", "GroupName", "Scenario", "PrimaryImplLang", "ExtraInformation", "Level", });
    internal_static_ServiceInstanceDTO_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ServiceInstanceDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ServiceInstanceDTO_descriptor,
        new java.lang.String[] { "Guid", "ServiceGuid", "DeployGuid", "ConnectionId", "ClientId", "TransportType", "RemoteAddress", "EndpointProtocol", "EndpointHost", "EndpointPort", "EndpointPath", "EndpointAddress", "Status", "StatusReason", "Version", "Zone", "Weight", "MetadataJson", });
    internal_static_NamespaceNodeDTO_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_NamespaceNodeDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NamespaceNodeDTO_descriptor,
        new java.lang.String[] { "Guid", "Name", "Type", "Description", "Leaf", });
    internal_static_ServicePageReply_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_ServicePageReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ServicePageReply_descriptor,
        new java.lang.String[] { "Items", "Total", "Offset", "Limit", });
    internal_static_ServiceInstancePageReply_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_ServiceInstancePageReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ServiceInstancePageReply_descriptor,
        new java.lang.String[] { "Items", "Total", "Offset", "Limit", });
    internal_static_ServiceReply_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_ServiceReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ServiceReply_descriptor,
        new java.lang.String[] { "Service", });
    internal_static_ServiceInstanceReply_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_ServiceInstanceReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ServiceInstanceReply_descriptor,
        new java.lang.String[] { "Instance", });
    internal_static_NamespaceChildrenReply_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_NamespaceChildrenReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NamespaceChildrenReply_descriptor,
        new java.lang.String[] { "Items", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}



