<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.sauron</groupId>
        <artifactId>sauron</artifactId>
        <version>1.2.7</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <groupId>org.example</groupId>
    <artifactId>sparta-uis-console</artifactId>
    <packaging>jar</packaging>

    <name>sparta-yis-console</name>
    <url>http://maven.apache.org</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.pinecone.hydra.kernel</groupId>
            <artifactId>hydra-architecture</artifactId>
            <version>2.1.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.pinecone.summer.springram</groupId>
            <artifactId>springram</artifactId>
            <version>2.1.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.pinecone.tritium</groupId>
            <artifactId>hydra-system-tritium</artifactId>
            <version>2.1.0</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>
