syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.pinecone.hydra.service.registry.grpc.server.meta";
option java_outer_classname = "ServiceMetaProto";

package pinecone.meta;

service ServiceMeta {

  rpc FetchServiceInsMetaByClientId (ClientIdRequest) returns (ServiceMetaDTOListReply);

  rpc FetchServiceInsMetaByServiceId (ServiceIdRequest) returns (ServiceMetaDTOListReply);

  rpc QueryServiceMetaByPath (PathRequest) returns (ServiceMetaDTOReply);

  rpc QueryServiceMetaByGuid (GuidRequest) returns (ServiceMetaDTOReply);

  rpc EvalCreationStatement (EvalRequest) returns (StringReply);

  rpc CreateNewService (CreateNewServiceRequest) returns (StringReply);
}

/* ================= DTO ================= */

message ServiceMetaDTO {

  string guid = 1;

  string name = 2;

  string type = 3;

  string displayName = 4;

  string description = 5;

  string fullName = 6;

  string groupNamespace = 7;

  string groupName = 8;

  string scenario = 9;

  string primaryImplLang = 10;

  string extraInformation = 11;

  string level = 12;
}

/* ================= Request / Reply ================= */

message ClientIdRequest {
  int64 clientId = 1;
}

message ServiceIdRequest {
  string serviceId = 1;
}

message PathRequest {
  string path = 1;
}

message GuidRequest {
  string guid = 1;
}

message EvalRequest {
  string jsonStatement = 1;
}

message CreateNewServiceRequest {
  string parentAppPath = 1;
  ServiceMetaDTO meta = 2;
}

message ServiceMetaDTOReply {
  ServiceMetaDTO meta = 1;
}

message ServiceMetaDTOListReply {
  repeated ServiceMetaDTO metas = 1;
}

message StringReply {
  string value = 1;
}
