// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device_meta.proto

package com.acorn.skynet.device.grpc.protocol.meta.proto;

/**
 * Protobuf type {@code UpdateDeviceMetaByPathRequest}
 */
public final class UpdateDeviceMetaByPathRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:UpdateDeviceMetaByPathRequest)
    UpdateDeviceMetaByPathRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateDeviceMetaByPathRequest.newBuilder() to construct.
  private UpdateDeviceMetaByPathRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateDeviceMetaByPathRequest() {
    path_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateDeviceMetaByPathRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaProto.internal_static_UpdateDeviceMetaByPathRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaProto.internal_static_UpdateDeviceMetaByPathRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest.class, com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest.Builder.class);
  }

  private int bitField0_;
  public static final int PATH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object path_ = "";
  /**
   * <code>string path = 1;</code>
   * @return The path.
   */
  @java.lang.Override
  public java.lang.String getPath() {
    java.lang.Object ref = path_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      path_ = s;
      return s;
    }
  }
  /**
   * <code>string path = 1;</code>
   * @return The bytes for path.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPathBytes() {
    java.lang.Object ref = path_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      path_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int META_FIELD_NUMBER = 2;
  private com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTO meta_;
  /**
   * <code>.DeviceMetaDTO meta = 2;</code>
   * @return Whether the meta field is set.
   */
  @java.lang.Override
  public boolean hasMeta() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.DeviceMetaDTO meta = 2;</code>
   * @return The meta.
   */
  @java.lang.Override
  public com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTO getMeta() {
    return meta_ == null ? com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTO.getDefaultInstance() : meta_;
  }
  /**
   * <code>.DeviceMetaDTO meta = 2;</code>
   */
  @java.lang.Override
  public com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTOOrBuilder getMetaOrBuilder() {
    return meta_ == null ? com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTO.getDefaultInstance() : meta_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(path_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, path_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getMeta());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(path_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, path_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMeta());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest)) {
      return super.equals(obj);
    }
    com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest other = (com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest) obj;

    if (!getPath()
        .equals(other.getPath())) return false;
    if (hasMeta() != other.hasMeta()) return false;
    if (hasMeta()) {
      if (!getMeta()
          .equals(other.getMeta())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PATH_FIELD_NUMBER;
    hash = (53 * hash) + getPath().hashCode();
    if (hasMeta()) {
      hash = (37 * hash) + META_FIELD_NUMBER;
      hash = (53 * hash) + getMeta().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UpdateDeviceMetaByPathRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UpdateDeviceMetaByPathRequest)
      com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaProto.internal_static_UpdateDeviceMetaByPathRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaProto.internal_static_UpdateDeviceMetaByPathRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest.class, com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest.Builder.class);
    }

    // Construct using com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMetaFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      path_ = "";
      meta_ = null;
      if (metaBuilder_ != null) {
        metaBuilder_.dispose();
        metaBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaProto.internal_static_UpdateDeviceMetaByPathRequest_descriptor;
    }

    @java.lang.Override
    public com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest getDefaultInstanceForType() {
      return com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest build() {
      com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest buildPartial() {
      com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest result = new com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.path_ = path_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.meta_ = metaBuilder_ == null
            ? meta_
            : metaBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest) {
        return mergeFrom((com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest other) {
      if (other == com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest.getDefaultInstance()) return this;
      if (!other.getPath().isEmpty()) {
        path_ = other.path_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasMeta()) {
        mergeMeta(other.getMeta());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              path_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getMetaFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object path_ = "";
    /**
     * <code>string path = 1;</code>
     * @return The path.
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string path = 1;</code>
     * @return The bytes for path.
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string path = 1;</code>
     * @param value The path to set.
     * @return This builder for chaining.
     */
    public Builder setPath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      path_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string path = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPath() {
      path_ = getDefaultInstance().getPath();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string path = 1;</code>
     * @param value The bytes for path to set.
     * @return This builder for chaining.
     */
    public Builder setPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      path_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTO meta_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTO, com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTO.Builder, com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTOOrBuilder> metaBuilder_;
    /**
     * <code>.DeviceMetaDTO meta = 2;</code>
     * @return Whether the meta field is set.
     */
    public boolean hasMeta() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.DeviceMetaDTO meta = 2;</code>
     * @return The meta.
     */
    public com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTO getMeta() {
      if (metaBuilder_ == null) {
        return meta_ == null ? com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTO.getDefaultInstance() : meta_;
      } else {
        return metaBuilder_.getMessage();
      }
    }
    /**
     * <code>.DeviceMetaDTO meta = 2;</code>
     */
    public Builder setMeta(com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTO value) {
      if (metaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        meta_ = value;
      } else {
        metaBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.DeviceMetaDTO meta = 2;</code>
     */
    public Builder setMeta(
        com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTO.Builder builderForValue) {
      if (metaBuilder_ == null) {
        meta_ = builderForValue.build();
      } else {
        metaBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.DeviceMetaDTO meta = 2;</code>
     */
    public Builder mergeMeta(com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTO value) {
      if (metaBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          meta_ != null &&
          meta_ != com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTO.getDefaultInstance()) {
          getMetaBuilder().mergeFrom(value);
        } else {
          meta_ = value;
        }
      } else {
        metaBuilder_.mergeFrom(value);
      }
      if (meta_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.DeviceMetaDTO meta = 2;</code>
     */
    public Builder clearMeta() {
      bitField0_ = (bitField0_ & ~0x00000002);
      meta_ = null;
      if (metaBuilder_ != null) {
        metaBuilder_.dispose();
        metaBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.DeviceMetaDTO meta = 2;</code>
     */
    public com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTO.Builder getMetaBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getMetaFieldBuilder().getBuilder();
    }
    /**
     * <code>.DeviceMetaDTO meta = 2;</code>
     */
    public com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTOOrBuilder getMetaOrBuilder() {
      if (metaBuilder_ != null) {
        return metaBuilder_.getMessageOrBuilder();
      } else {
        return meta_ == null ?
            com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTO.getDefaultInstance() : meta_;
      }
    }
    /**
     * <code>.DeviceMetaDTO meta = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTO, com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTO.Builder, com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTOOrBuilder> 
        getMetaFieldBuilder() {
      if (metaBuilder_ == null) {
        metaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTO, com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTO.Builder, com.acorn.skynet.device.grpc.protocol.meta.proto.DeviceMetaDTOOrBuilder>(
                getMeta(),
                getParentForChildren(),
                isClean());
        meta_ = null;
      }
      return metaBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:UpdateDeviceMetaByPathRequest)
  }

  // @@protoc_insertion_point(class_scope:UpdateDeviceMetaByPathRequest)
  private static final com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest();
  }

  public static com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateDeviceMetaByPathRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateDeviceMetaByPathRequest>() {
    @java.lang.Override
    public UpdateDeviceMetaByPathRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpdateDeviceMetaByPathRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateDeviceMetaByPathRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.acorn.skynet.device.grpc.protocol.meta.proto.UpdateDeviceMetaByPathRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

