// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remote_process_lifecycle.proto

package com.walnut.odin.proc.server.transport.grpc.lifecycle;

/**
 * Protobuf type {@code walnut.odin.proc.control.lifecycle.HeartbeatFrame}
 */
public final class HeartbeatFrame extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:walnut.odin.proc.control.lifecycle.HeartbeatFrame)
    HeartbeatFrameOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HeartbeatFrame.newBuilder() to construct.
  private HeartbeatFrame(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HeartbeatFrame() {
    status_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HeartbeatFrame();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.walnut.odin.proc.server.transport.grpc.lifecycle.RemoteProcessLifecycleProto.internal_static_walnut_odin_proc_control_lifecycle_HeartbeatFrame_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.walnut.odin.proc.server.transport.grpc.lifecycle.RemoteProcessLifecycleProto.internal_static_walnut_odin_proc_control_lifecycle_HeartbeatFrame_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame.class, com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame.Builder.class);
  }

  public static final int TIMESTAMP_MILLIS_FIELD_NUMBER = 1;
  private long timestampMillis_ = 0L;
  /**
   * <code>int64 timestamp_millis = 1;</code>
   * @return The timestampMillis.
   */
  @java.lang.Override
  public long getTimestampMillis() {
    return timestampMillis_;
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <code>string status = 2;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timestampMillis_ != 0L) {
      output.writeInt64(1, timestampMillis_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, status_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timestampMillis_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, timestampMillis_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, status_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame)) {
      return super.equals(obj);
    }
    com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame other = (com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame) obj;

    if (getTimestampMillis()
        != other.getTimestampMillis()) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIMESTAMP_MILLIS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestampMillis());
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code walnut.odin.proc.control.lifecycle.HeartbeatFrame}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:walnut.odin.proc.control.lifecycle.HeartbeatFrame)
      com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrameOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.walnut.odin.proc.server.transport.grpc.lifecycle.RemoteProcessLifecycleProto.internal_static_walnut_odin_proc_control_lifecycle_HeartbeatFrame_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.walnut.odin.proc.server.transport.grpc.lifecycle.RemoteProcessLifecycleProto.internal_static_walnut_odin_proc_control_lifecycle_HeartbeatFrame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame.class, com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame.Builder.class);
    }

    // Construct using com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      timestampMillis_ = 0L;
      status_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.walnut.odin.proc.server.transport.grpc.lifecycle.RemoteProcessLifecycleProto.internal_static_walnut_odin_proc_control_lifecycle_HeartbeatFrame_descriptor;
    }

    @java.lang.Override
    public com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame getDefaultInstanceForType() {
      return com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame.getDefaultInstance();
    }

    @java.lang.Override
    public com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame build() {
      com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame buildPartial() {
      com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame result = new com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.timestampMillis_ = timestampMillis_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.status_ = status_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame) {
        return mergeFrom((com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame other) {
      if (other == com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame.getDefaultInstance()) return this;
      if (other.getTimestampMillis() != 0L) {
        setTimestampMillis(other.getTimestampMillis());
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              timestampMillis_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long timestampMillis_ ;
    /**
     * <code>int64 timestamp_millis = 1;</code>
     * @return The timestampMillis.
     */
    @java.lang.Override
    public long getTimestampMillis() {
      return timestampMillis_;
    }
    /**
     * <code>int64 timestamp_millis = 1;</code>
     * @param value The timestampMillis to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampMillis(long value) {

      timestampMillis_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp_millis = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestampMillis() {
      bitField0_ = (bitField0_ & ~0x00000001);
      timestampMillis_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 2;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 2;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 2;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string status = 2;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:walnut.odin.proc.control.lifecycle.HeartbeatFrame)
  }

  // @@protoc_insertion_point(class_scope:walnut.odin.proc.control.lifecycle.HeartbeatFrame)
  private static final com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame();
  }

  public static com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HeartbeatFrame>
      PARSER = new com.google.protobuf.AbstractParser<HeartbeatFrame>() {
    @java.lang.Override
    public HeartbeatFrame parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HeartbeatFrame> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HeartbeatFrame> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.walnut.odin.proc.server.transport.grpc.lifecycle.HeartbeatFrame getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

