// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remote_process_lifecycle.proto

package com.walnut.odin.proc.server.transport.grpc.lifecycle;

public interface HeartbeatFrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:walnut.odin.proc.control.lifecycle.HeartbeatFrame)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 timestamp_millis = 1;</code>
   * @return The timestampMillis.
   */
  long getTimestampMillis();

  /**
   * <code>string status = 2;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
