// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remote_process_lifecycle.proto

package com.walnut.odin.proc.server.transport.grpc.lifecycle;

/**
 * Protobuf enum {@code walnut.odin.proc.control.lifecycle.RemoteProcessControlFrameType}
 */
public enum RemoteProcessControlFrameType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>REMOTE_PROCESS_CONTROL_FRAME_TYPE_UNSPECIFIED = 0;</code>
   */
  REMOTE_PROCESS_CONTROL_FRAME_TYPE_UNSPECIFIED(0),
  /**
   * <code>CLIENT_MUSTER = 1;</code>
   */
  CLIENT_MUSTER(1),
  /**
   * <code>CLIENT_READY = 2;</code>
   */
  CLIENT_READY(2),
  /**
   * <code>CREATE_REMOTE_PROCESS = 10;</code>
   */
  CREATE_REMOTE_PROCESS(10),
  /**
   * <code>VITALIZE_REMOTE_PROCESS = 11;</code>
   */
  VITALIZE_REMOTE_PROCESS(11),
  /**
   * <code>START_REMOTE_PROCESS = 12;</code>
   */
  START_REMOTE_PROCESS(12),
  /**
   * <code>QUERY_PROCESS_RUNTIME_META = 13;</code>
   */
  QUERY_PROCESS_RUNTIME_META(13),
  /**
   * <code>HAS_OWN_PROCESS = 14;</code>
   */
  HAS_OWN_PROCESS(14),
  /**
   * <code>CONTAIN_PROCESS = 15;</code>
   */
  CONTAIN_PROCESS(15),
  /**
   * <code>COMMAND_RESULT = 30;</code>
   */
  COMMAND_RESULT(30),
  /**
   * <code>PROCESS_CREATED = 31;</code>
   */
  PROCESS_CREATED(31),
  /**
   * <code>PROCESS_TERMINATED = 32;</code>
   */
  PROCESS_TERMINATED(32),
  /**
   * <code>PROCESS_RUNTIME_META = 33;</code>
   */
  PROCESS_RUNTIME_META(33),
  /**
   * <code>HEARTBEAT = 50;</code>
   */
  HEARTBEAT(50),
  /**
   * <code>APOPTOSIS = 60;</code>
   */
  APOPTOSIS(60),
  /**
   * <code>ERROR = 90;</code>
   */
  ERROR(90),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>REMOTE_PROCESS_CONTROL_FRAME_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int REMOTE_PROCESS_CONTROL_FRAME_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>CLIENT_MUSTER = 1;</code>
   */
  public static final int CLIENT_MUSTER_VALUE = 1;
  /**
   * <code>CLIENT_READY = 2;</code>
   */
  public static final int CLIENT_READY_VALUE = 2;
  /**
   * <code>CREATE_REMOTE_PROCESS = 10;</code>
   */
  public static final int CREATE_REMOTE_PROCESS_VALUE = 10;
  /**
   * <code>VITALIZE_REMOTE_PROCESS = 11;</code>
   */
  public static final int VITALIZE_REMOTE_PROCESS_VALUE = 11;
  /**
   * <code>START_REMOTE_PROCESS = 12;</code>
   */
  public static final int START_REMOTE_PROCESS_VALUE = 12;
  /**
   * <code>QUERY_PROCESS_RUNTIME_META = 13;</code>
   */
  public static final int QUERY_PROCESS_RUNTIME_META_VALUE = 13;
  /**
   * <code>HAS_OWN_PROCESS = 14;</code>
   */
  public static final int HAS_OWN_PROCESS_VALUE = 14;
  /**
   * <code>CONTAIN_PROCESS = 15;</code>
   */
  public static final int CONTAIN_PROCESS_VALUE = 15;
  /**
   * <code>COMMAND_RESULT = 30;</code>
   */
  public static final int COMMAND_RESULT_VALUE = 30;
  /**
   * <code>PROCESS_CREATED = 31;</code>
   */
  public static final int PROCESS_CREATED_VALUE = 31;
  /**
   * <code>PROCESS_TERMINATED = 32;</code>
   */
  public static final int PROCESS_TERMINATED_VALUE = 32;
  /**
   * <code>PROCESS_RUNTIME_META = 33;</code>
   */
  public static final int PROCESS_RUNTIME_META_VALUE = 33;
  /**
   * <code>HEARTBEAT = 50;</code>
   */
  public static final int HEARTBEAT_VALUE = 50;
  /**
   * <code>APOPTOSIS = 60;</code>
   */
  public static final int APOPTOSIS_VALUE = 60;
  /**
   * <code>ERROR = 90;</code>
   */
  public static final int ERROR_VALUE = 90;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RemoteProcessControlFrameType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static RemoteProcessControlFrameType forNumber(int value) {
    switch (value) {
      case 0: return REMOTE_PROCESS_CONTROL_FRAME_TYPE_UNSPECIFIED;
      case 1: return CLIENT_MUSTER;
      case 2: return CLIENT_READY;
      case 10: return CREATE_REMOTE_PROCESS;
      case 11: return VITALIZE_REMOTE_PROCESS;
      case 12: return START_REMOTE_PROCESS;
      case 13: return QUERY_PROCESS_RUNTIME_META;
      case 14: return HAS_OWN_PROCESS;
      case 15: return CONTAIN_PROCESS;
      case 30: return COMMAND_RESULT;
      case 31: return PROCESS_CREATED;
      case 32: return PROCESS_TERMINATED;
      case 33: return PROCESS_RUNTIME_META;
      case 50: return HEARTBEAT;
      case 60: return APOPTOSIS;
      case 90: return ERROR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RemoteProcessControlFrameType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RemoteProcessControlFrameType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RemoteProcessControlFrameType>() {
          public RemoteProcessControlFrameType findValueByNumber(int number) {
            return RemoteProcessControlFrameType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.walnut.odin.proc.server.transport.grpc.lifecycle.RemoteProcessLifecycleProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final RemoteProcessControlFrameType[] VALUES = values();

  public static RemoteProcessControlFrameType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RemoteProcessControlFrameType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:walnut.odin.proc.control.lifecycle.RemoteProcessControlFrameType)
}

