// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_control.proto

package com.acorn.redqueen.service.registry.grpc.protocol.lifecycle.proto;

public interface RegisterServiceCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RegisterServiceCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serviceGuid = 1;</code>
   * @return The serviceGuid.
   */
  java.lang.String getServiceGuid();
  /**
   * <code>string serviceGuid = 1;</code>
   * @return The bytes for serviceGuid.
   */
  com.google.protobuf.ByteString
      getServiceGuidBytes();

  /**
   * <code>string deployGuid = 2;</code>
   * @return The deployGuid.
   */
  java.lang.String getDeployGuid();
  /**
   * <code>string deployGuid = 2;</code>
   * @return The bytes for deployGuid.
   */
  com.google.protobuf.ByteString
      getDeployGuidBytes();

  /**
   * <code>string endpointProtocol = 3;</code>
   * @return The endpointProtocol.
   */
  java.lang.String getEndpointProtocol();
  /**
   * <code>string endpointProtocol = 3;</code>
   * @return The bytes for endpointProtocol.
   */
  com.google.protobuf.ByteString
      getEndpointProtocolBytes();

  /**
   * <code>string endpointHost = 4;</code>
   * @return The endpointHost.
   */
  java.lang.String getEndpointHost();
  /**
   * <code>string endpointHost = 4;</code>
   * @return The bytes for endpointHost.
   */
  com.google.protobuf.ByteString
      getEndpointHostBytes();

  /**
   * <code>int32 endpointPort = 5;</code>
   * @return The endpointPort.
   */
  int getEndpointPort();

  /**
   * <code>string endpointPath = 6;</code>
   * @return The endpointPath.
   */
  java.lang.String getEndpointPath();
  /**
   * <code>string endpointPath = 6;</code>
   * @return The bytes for endpointPath.
   */
  com.google.protobuf.ByteString
      getEndpointPathBytes();

  /**
   * <code>string endpointAddress = 7;</code>
   * @return The endpointAddress.
   */
  java.lang.String getEndpointAddress();
  /**
   * <code>string endpointAddress = 7;</code>
   * @return The bytes for endpointAddress.
   */
  com.google.protobuf.ByteString
      getEndpointAddressBytes();

  /**
   * <code>string version = 8;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 8;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string zone = 9;</code>
   * @return The zone.
   */
  java.lang.String getZone();
  /**
   * <code>string zone = 9;</code>
   * @return The bytes for zone.
   */
  com.google.protobuf.ByteString
      getZoneBytes();

  /**
   * <code>int32 weight = 10;</code>
   * @return The weight.
   */
  int getWeight();

  /**
   * <code>repeated string tags = 11;</code>
   * @return A list containing the tags.
   */
  java.util.List<java.lang.String>
      getTagsList();
  /**
   * <code>repeated string tags = 11;</code>
   * @return The count of tags.
   */
  int getTagsCount();
  /**
   * <code>repeated string tags = 11;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  java.lang.String getTags(int index);
  /**
   * <code>repeated string tags = 11;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);

  /**
   * <code>string metadataJson = 12;</code>
   * @return The metadataJson.
   */
  java.lang.String getMetadataJson();
  /**
   * <code>string metadataJson = 12;</code>
   * @return The bytes for metadataJson.
   */
  com.google.protobuf.ByteString
      getMetadataJsonBytes();

  /**
   * <code>int64 heartbeatIntervalMillis = 13;</code>
   * @return The heartbeatIntervalMillis.
   */
  long getHeartbeatIntervalMillis();

  /**
   * <code>int64 leaseTimeoutMillis = 14;</code>
   * @return The leaseTimeoutMillis.
   */
  long getLeaseTimeoutMillis();

  /**
   * <code>string instanceGuid = 15;</code>
   * @return The instanceGuid.
   */
  java.lang.String getInstanceGuid();
  /**
   * <code>string instanceGuid = 15;</code>
   * @return The bytes for instanceGuid.
   */
  com.google.protobuf.ByteString
      getInstanceGuidBytes();

  /**
   * <code>string runtimeNodeId = 16;</code>
   * @return The runtimeNodeId.
   */
  java.lang.String getRuntimeNodeId();
  /**
   * <code>string runtimeNodeId = 16;</code>
   * @return The bytes for runtimeNodeId.
   */
  com.google.protobuf.ByteString
      getRuntimeNodeIdBytes();

  /**
   * <code>string runtimeNodeAlias = 17;</code>
   * @return The runtimeNodeAlias.
   */
  java.lang.String getRuntimeNodeAlias();
  /**
   * <code>string runtimeNodeAlias = 17;</code>
   * @return The bytes for runtimeNodeAlias.
   */
  com.google.protobuf.ByteString
      getRuntimeNodeAliasBytes();

  /**
   * <code>string runtimeNodeMetadataJson = 18;</code>
   * @return The runtimeNodeMetadataJson.
   */
  java.lang.String getRuntimeNodeMetadataJson();
  /**
   * <code>string runtimeNodeMetadataJson = 18;</code>
   * @return The bytes for runtimeNodeMetadataJson.
   */
  com.google.protobuf.ByteString
      getRuntimeNodeMetadataJsonBytes();
}
