// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service_control.proto
// Protobuf Java Version: 4.28.2

package com.acorn.redqueen.service.registry.grpc.protocol.lifecycle.proto;

/**
 * Protobuf enum {@code ServiceControlFrameType}
 */
public enum ServiceControlFrameType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN = 0;</code>
   */
  UNKNOWN(0),
  /**
   * <code>CLIENT_MUSTER = 1;</code>
   */
  CLIENT_MUSTER(1),
  /**
   * <code>CLIENT_READY = 2;</code>
   */
  CLIENT_READY(2),
  /**
   * <code>REGISTER_SERVICE = 3;</code>
   */
  REGISTER_SERVICE(3),
  /**
   * <code>REGISTER_ACCEPTED = 4;</code>
   */
  REGISTER_ACCEPTED(4),
  /**
   * <code>HEARTBEAT = 5;</code>
   */
  HEARTBEAT(5),
  /**
   * <code>DEREGISTER = 6;</code>
   */
  DEREGISTER(6),
  /**
   * <code>DEREGISTERED = 7;</code>
   */
  DEREGISTERED(7),
  /**
   * <code>SHUTDOWN_SERVICE = 8;</code>
   */
  SHUTDOWN_SERVICE(8),
  /**
   * <code>SHUTDOWN_ACCEPTED = 9;</code>
   */
  SHUTDOWN_ACCEPTED(9),
  /**
   * <code>ERROR = 10;</code>
   */
  ERROR(10),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      ServiceControlFrameType.class.getName());
  }
  /**
   * <code>UNKNOWN = 0;</code>
   */
  public static final int UNKNOWN_VALUE = 0;
  /**
   * <code>CLIENT_MUSTER = 1;</code>
   */
  public static final int CLIENT_MUSTER_VALUE = 1;
  /**
   * <code>CLIENT_READY = 2;</code>
   */
  public static final int CLIENT_READY_VALUE = 2;
  /**
   * <code>REGISTER_SERVICE = 3;</code>
   */
  public static final int REGISTER_SERVICE_VALUE = 3;
  /**
   * <code>REGISTER_ACCEPTED = 4;</code>
   */
  public static final int REGISTER_ACCEPTED_VALUE = 4;
  /**
   * <code>HEARTBEAT = 5;</code>
   */
  public static final int HEARTBEAT_VALUE = 5;
  /**
   * <code>DEREGISTER = 6;</code>
   */
  public static final int DEREGISTER_VALUE = 6;
  /**
   * <code>DEREGISTERED = 7;</code>
   */
  public static final int DEREGISTERED_VALUE = 7;
  /**
   * <code>SHUTDOWN_SERVICE = 8;</code>
   */
  public static final int SHUTDOWN_SERVICE_VALUE = 8;
  /**
   * <code>SHUTDOWN_ACCEPTED = 9;</code>
   */
  public static final int SHUTDOWN_ACCEPTED_VALUE = 9;
  /**
   * <code>ERROR = 10;</code>
   */
  public static final int ERROR_VALUE = 10;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ServiceControlFrameType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ServiceControlFrameType forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN;
      case 1: return CLIENT_MUSTER;
      case 2: return CLIENT_READY;
      case 3: return REGISTER_SERVICE;
      case 4: return REGISTER_ACCEPTED;
      case 5: return HEARTBEAT;
      case 6: return DEREGISTER;
      case 7: return DEREGISTERED;
      case 8: return SHUTDOWN_SERVICE;
      case 9: return SHUTDOWN_ACCEPTED;
      case 10: return ERROR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ServiceControlFrameType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ServiceControlFrameType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ServiceControlFrameType>() {
          public ServiceControlFrameType findValueByNumber(int number) {
            return ServiceControlFrameType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.acorn.redqueen.service.registry.grpc.protocol.lifecycle.proto.ServiceControlProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final ServiceControlFrameType[] VALUES = values();

  public static ServiceControlFrameType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ServiceControlFrameType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ServiceControlFrameType)
}

